### ISSUE TITLE
Matchmaking

### ISSUE THREAD

**Issue by Vrekt** [RobertoGraham/fortnite-2#10]
Wanted to make a separate issue dedicated to matchmaking features since the other one is for friends.

Here are some interesting matchmaking endpoints [here](https://github.com/SzymonLisowiec/node-epicgames-fortnite-client/blob/master/resources/Endpoint.js)

**Comment by Vrekt** [comment]
I added a few methods within your API and I'm currently exploring the endpoints. Ill update this issue further if i find anything interesting that is worth adding. Ill create a pull request if I add anything significant/useful.

**Comment by Vrekt** [comment]
Looks like you can get placement/score from the in-game tournaments from this URI:

```
https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/game/v2/events/v2/history/eventandscore/<account id>/NAE/Windows
```

**Comment by Vrekt** [comment]
I've looked but I've found no way, when I was joining another player or creating a server myself it connected to an XMPP server and got the session id that way. Here is a log: https://pastebin.com/C4C13xMn

At line 1 you can see the server it connects to and you will see it updates from "queue full" to "connecting", "inqueue", etc. At line 26-30 is where it waits to get assigned a session id and then finally it gets assigned a match id, the session id and a join delay. Once the session id is assigned it uses normal requests to the matchmaking endpoints I mentioned earlier [here](https://github.com/SzymonLisowiec/node-epicgames-fortnite-client/blob/master/resources/Endpoint.js) to join the match or whatever else needs to be done.

**Comment by Vrekt** [comment]
Also when I said "I've looked but I've found no way", means I have not found a way *yet*, BUT I know it is possible.

**Comment by Vrekt** [comment]
Not sure what the match id is for, could just be an internal type thing that isn't really used but I was surprised to learn it was a session id and not the match id.

**Comment by Vrekt** [comment]
Also getting a bit spammy here but, I honestly don't know much about HTTP/requests, json, etc. But I can bet that getting a session id is something super simple just like getting account Ids/stats, etc is. Also don't have much experience with Fiddler/wireshark so its really hard to get the requests

**Comment by Vrekt** [comment]
https://github.com/RobertoGraham/fortnite-2-xmpp

https://github.com/SzymonLisowiec/node-epicgames-client

https://github.com/Vrekt/FortniteXMPP

**Comment by Beat-YT** [comment]
> now if I only I could figure out how to actually get the session ID we could add some neat features into your API.

You need to use websocket

**Comment by zamzoum94** [comment]
Hello guys, I was looking for to create custum matches via api, is it possible?
