### ISSUE TITLE
Upgrade to Java 11 discussion thread - 28 days

### ISSUE THREAD

**Issue by RobertoGraham** [RobertoGraham/fortnite-2#5]
Since Java 8 will lose Oracle support next month I would like to make this library support only Java 11+. If anybody wants me to maintain library support for Java 8 I will provide an alternate "fortnite-2-java-11" dependency released from a secondary branch.

**Comment by Vrekt** [comment]
I agree with your decision, also great project you have here.

**Comment by RobertoGraham** [comment]
Upgraded to JDK 11, v2.0.0 will be available on The Central Repository in a couple of hours.
