### ISSUE TITLE
Implement Friends API Support

### ISSUE THREAD

**Issue by RobertoGraham** [RobertoGraham/fortnite-2#7]

**Comment by chaudharydeepak** [comment]
I can help contribute.

**Comment by Vrekt** [comment]
Looking in fiddler deleting goes something like this:

``DELETE https://friends-public-service-prod06.ol.epicgames.com/friends/api/public/friends/YOUR_USER_ID/USER_TO_DELETE_ID``

I also found an older API that was released almost a year ago that has a basic friends support [here](https://github.com/Xilixir/FortniteAPI/commit/080b3f638bfe6982f5ab965fff42b1eef06cd57b)
